# Generated by Django 4.2.4 on 2023-12-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tags", to="blog.tag"
            ),
        ),
    ]
